services:
  lineprovider:
    build: ./lineprovider
    container_name: lineprovider
    ports:
      - 8080:8080
    environment:
      - BET_MAKER_CALLBACK_URL=http://betmaker:9090/callback
    volumes:
      - ./common:/opt/common
    depends_on:
      - betmaker

  betmaker:
    build: ./betmaker
    container_name: betmaker
    ports:
      - 9090:9090
    depends_on:
      betmaker-db:
        condition: service_healthy
    environment:
      - LINE_PROVIDER_URL=http://lineprovider:8080
      - DATABASE_URL=postgresql+asyncpg://xxx:yyy@betmaker-db:5432/betmaker
    volumes:
      - ./common:/opt/common

  betmaker-db:
    image: postgres:15
    container_name: betmaker-db
    environment:
      - POSTGRES_DB=betmaker
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=yyy
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
